language: php

sudo: false

php:
  - 7.1

env:
  matrix:
    - DB=mysql db_class='Cake\Database\Driver\Mysql' db_dsn='mysql:host=0.0.0.0;dbname=cakephp_test' db_database='cakephp_test' db_username='travis' db_password=''
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.1
      env: DB=pgsql db_class='Cake\Database\Driver\Postgres' db_dsn='postgres://postgres@127.0.0.1/cakephp_test' db_database='cakephp_test' db_username='travis' db_password=''

    - php: 7.1
      env: PHPCS=1 DEFAULT=0

    - php: 7.1
      env: CODECOVERAGE=1 DEFAULT=0

before_script:
  - sudo apt-get -qq update > /dev/null
  - sudo apt-get -qq install graphviz > /dev/null
  - composer install --prefer-source --no-interaction

  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"

  - phpenv rehash
  - set +H
  - cp phpunit.xml.dist phpunit.xml

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then composer cs-check ; fi"

  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then phpunit --coverage-clover=clover.xml || true; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then wget -O codecov.sh https://codecov.io/bash; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then bash codecov.sh; fi"

notifications:
  email: false
